(dp1
S'output'
p2
S'<class \'gluon.contrib.pymysql.err.InternalError\'> (1025, u"Error on rename of \'.\\\\mydb\\\\#sql-3650_41\' to \'.\\\\mydb\\\\filho\' (errno: 150)")'
p3
sS'layer'
p4
S'C:\\Users\\Leandro\\Documents\\CJR\\DIPRO\\PROJETOS\\G\xeanios\\genios\\ProjetoGenios\\web2py\\applications\\Genios\\models\\db.py'
p5
sS'code'
p6
S"db = DAL('mysql://root:Ca_784595@localhost/mydb') # Conecta com o banco\n\n\ndb.define_table('pai',Field('nome'),Field('ativo','boolean'),Field('nome','text'),format = '%(nome)s')\ndb.define_table('filho',\n                Field('foto','upload', uploadfield='foto_arquivo'),\n                Field('foto_arquivo','blob'),Field('ativo','boolean'),\n                Field('nome'),format = '%(nome)s')\ndb.define_table('pai_x_filho',Field('fk_pai','reference pai'),Field('fk_filho','reference filho') )\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/restricted.py", line 220, in restricted\n  File "C:\\Users\\Leandro\\Documents\\CJR\\DIPRO\\PROJETOS\\G\xeanios\\genios\\ProjetoGenios\\web2py\\applications\\Genios\\models\\db.py", line 8, in <module>\n    Field(\'nome\'),format = \'%(nome)s\')\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 8223, in define_table\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 8260, in lazy_define_table\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 1132, in create_table\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 1245, in migrate_table\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 1969, in execute\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 1963, in log_execute\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/cursors.py", line 117, in execute\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 202, in defaulterrorhandler\nInternalError: (1025, u"Error on rename of \'.\\\\mydb\\\\#sql-3650_41\' to \'.\\\\mydb\\\\filho\' (errno: 150)")\n'
p11
s.